[
	{
		id: 'help',
		categoryID: 'General',
		category: ['help', 'ping', 'server'],
		filepath:
			'C:\\Users\\MyPC\\Documents\\enma\\src\\commands\\General\\help.ts',
		aliases: ['help', 'h'],
		channel: null,
		ownerOnly: false,
		editable: true,
		typing: false,
		cooldown: null,
		ratelimit: 2,
		clientPermissions: ['EMBED_LINKS'],
	},
	{
		id: 'ping',
		categoryID: 'General',
		category: ['help', 'ping', 'server'],
		filepath:
			'C:\\Users\\MyPC\\Documents\\enma\\src\\commands\\General\\ping.ts',
		aliases: ['ping', 'pong'],
		channel: null,
		ownerOnly: false,
		editable: true,
		typing: false,
		cooldown: null,
		ratelimit: 1,
		clientPermissions: ['EMBED_LINKS'],
	},
	{
		id: 'server',
		categoryID: 'General',
		category: ['help', 'ping', 'server'],
		filepath:
			'C:\\Users\\MyPC\\Documents\\enma\\src\\commands\\General\\serverinfo.ts',
		aliases: ['server', 'guild', 'guildinfo'],
		channel: null,
		ownerOnly: false,
		editable: true,
		typing: false,
		cooldown: null,
		ratelimit: 1,
	},
	{
		id: 'lyrics',
		categoryID: 'Music',
		category: [
			'lyrics',
			'pause',
			'play',
			'queue',
			'resume',
			'search',
			'skip',
		],
		filepath:
			'C:\\Users\\MyPC\\Documents\\enma\\src\\commands\\Music\\lyrics.ts',
		aliases: ['lyrics', 'ly'],
		channel: null,
		ownerOnly: false,
		editable: true,
		typing: false,
		cooldown: null,
		ratelimit: 1,
	},
	{
		id: 'pause',
		categoryID: 'Music',
		category: [
			'lyrics',
			'pause',
			'play',
			'queue',
			'resume',
			'search',
			'skip',
		],
		filepath:
			'C:\\Users\\MyPC\\Documents\\enma\\src\\commands\\Music\\pause.ts',
		aliases: ['pause'],
		channel: null,
		ownerOnly: false,
		editable: true,
		typing: false,
		cooldown: null,
		ratelimit: 1,
	},
	{
		id: 'play',
		categoryID: 'Music',
		category: [
			'lyrics',
			'pause',
			'play',
			'queue',
			'resume',
			'search',
			'skip',
		],
		filepath:
			'C:\\Users\\MyPC\\Documents\\enma\\src\\commands\\Music\\play.ts',
		aliases: ['play', 'p'],
		channel: null,
		ownerOnly: false,
		editable: true,
		typing: false,
		cooldown: null,
		ratelimit: 1,
		clientPermissions: ['CONNECT', 'SPEAK'],
	},
	{
		id: 'queue',
		categoryID: 'Music',
		category: [
			'lyrics',
			'pause',
			'play',
			'queue',
			'resume',
			'search',
			'skip',
		],
		filepath:
			'C:\\Users\\MyPC\\Documents\\enma\\src\\commands\\Music\\queue.ts',
		aliases: ['queue', 'q'],
		channel: null,
		ownerOnly: false,
		editable: true,
		typing: false,
		cooldown: null,
		ratelimit: 1,
	},
	{
		id: 'resume',
		categoryID: 'Music',
		category: [
			'lyrics',
			'pause',
			'play',
			'queue',
			'resume',
			'search',
			'skip',
		],
		filepath:
			'C:\\Users\\MyPC\\Documents\\enma\\src\\commands\\Music\\resume.ts',
		aliases: ['resume'],
		channel: null,
		ownerOnly: false,
		editable: true,
		typing: false,
		cooldown: null,
		ratelimit: 1,
	},
	{
		id: 'search',
		categoryID: 'Music',
		category: [
			'lyrics',
			'pause',
			'play',
			'queue',
			'resume',
			'search',
			'skip',
		],
		filepath:
			'C:\\Users\\MyPC\\Documents\\enma\\src\\commands\\Music\\search.ts',
		aliases: ['search', 'sr'],
		channel: null,
		ownerOnly: false,
		editable: true,
		typing: false,
		cooldown: null,
		ratelimit: 1,
	},
	{
		id: 'skip',
		categoryID: 'Music',
		category: [
			'lyrics',
			'pause',
			'play',
			'queue',
			'resume',
			'search',
			'skip',
		],
		filepath:
			'C:\\Users\\MyPC\\Documents\\enma\\src\\commands\\Music\\skip.ts',
		aliases: ['skip', 's'],
		channel: null,
		ownerOnly: false,
		editable: true,
		typing: false,
		cooldown: null,
		ratelimit: 1,
	},
];
